### ISSUE TITLE
关于U-net的执行顺序问题

### ISSUE THREAD

**Issue by myboyliu** [silencemao/detect-cell-edge-use-unet#1]
您好：
在看了您的代码后觉得很有帮助，但是readme写的不是很清楚。
目前不知道执行顺序。
2 data augmentation the data and label should be the same change
对于步骤2，先执行data.py，然后执行augdata.py？
目前出错，错误日志如下：
loading data
------------------------------
load train images...
------------------------------
------------------------------
load test images...
------------------------------
loading data done
/Users/ericliu/cv/detect-cell-edge-use-unet/data.py:231: RuntimeWarning: Mean of empty slice.
  mean = imgs_test.mean(axis=0)
/Users/ericliu/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Traceback (most recent call last):
  File "/Users/ericliu/cv/detect-cell-edge-use-unet/unet_test.py", line 169, in <module>
    myunet.train()
  File "/Users/ericliu/cv/detect-cell-edge-use-unet/unet_test.py", line 153, in train
    model = self.get_unet()
  File "/Users/ericliu/cv/detect-cell-edge-use-unet/unet_test.py", line 87, in get_unet
    print("conv1 shape:", conv1.shape)
AttributeError: 'Tensor' object has no attribute 'shape'

Process finished with exit code 1

**Comment by myboyliu** [comment]
看了你的博客，应该是TensorFlow版本的问题。升级为1.2.1后没有那个错误了。

**Comment by Manfestain** [comment]
![default](https://user-images.githubusercontent.com/30315663/37941242-e29d001a-319f-11e8-8eea-3e88610beccc.png)
得到的predict效果好差，楼主能不能给点建议呀

**Comment by Manfestain** [comment]
我看了一下，是load_weights没加载上，应该是hdf5库的问题
